### ISSUE TITLE
Getting 'Unable to connect to remote debugger' from android emulator

### ISSUE THREAD

**Issue by esakal** [bartonhammond/snowflake#107]
Hello,
I cloned the project and successfully managed to run the application. But when I try debugging the application I'm getting the error 'Getting 'Unable to connect to remote debugger'

I can debug other applications but not this one. Please view the below screenshot:
![react-native-snoflake-error](https://cloud.githubusercontent.com/assets/4751797/16964290/4baa152a-4e03-11e6-89fb-7843afa65272.jpg)

Thanks!
Eran.

**Comment by bartonhammond** [comment]
Thanks @esakal - I can reproduce.  It's also been reported [https://github.com/facebook/react-native/issues/6390](https://github.com/facebook/react-native/issues/6390).  I am currently upgrading (attempting to anyway) to RN 29.  If you can figure it out, please make a PR.  Otherwise, you might have to wait until I get the next upgrade and I'm not exactly sure when that will be (sorry).

**Comment by jhabdas** [comment]
Couple of workarounds added for those experiencing this: https://github.com/facebook/react-native/issues/6390#issuecomment-236678286
