### ISSUE TITLE
Reducer resolution

### ISSUE THREAD

**Issue by sudham** [bartonhammond/snowflake#137]
How does this get resolved ? I am new to react redux - this is a bit confusing! Does this resolve to rootReducer ?
/**
* ## Reducer
* The reducer contains the 4 reducers from 
* device, global, auth, profile
*/
import reducer from '../reducers';

**Comment by bartonhammond** [comment]
What file are you looking at? The `src/reducers/index.js` combines the 4 reducers into a `rootReducer`

**Comment by sudham** [comment]
This import statement is in configStore.js - reproduced below.
 
/**
 * # configureStore.js
 * 
 * A Redux boilerplate setup
 * 
 */
'use strict';

/**
 * ## Imports
 * 
 * redux functions
 */
import { createStore, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';

/**
* ## Reducer
* The reducer contains the 4 reducers from 
* device, global, auth, profile
*/
import reducer from '../reducers';

/**
 * ## creatStoreWithMiddleware
 * Like the name...
 */ 
const createStoreWithMiddleware = applyMiddleware(
  thunk
)(createStore);

/**
 * ## configureStore
 * @param {Object} the state with for keys:
 * device, global, auth, profile
 * 
 */ 
export default function configureStore(initialState) {
  return createStoreWithMiddleware(reducer, initialState);
};

**Comment by bartonhammond** [comment]
This is not a `Redux` question, but rather an `import` question.  

If you create an `index.js` file in some directory, as in our case `src/reducers`, in order to import that file you can use `import reducer from '../reducers'` which is equivalent to `import reducer from `'../reducers/index'`  

See this discussion [http://stackoverflow.com/questions/35442174/javascript-import-from-folder-with-index-js](http://stackoverflow.com/questions/35442174/javascript-import-from-folder-with-index-js)
