### ISSUE TITLE
New version not working on android

### ISSUE THREAD

**Issue by ramsestom** [bartonhammond/snowflake#140]
I. I just updated to the latest version but can't make it work properly on android. I have a green spining wheel under the snoflakes logo that spin indefinitively. The console do not show any error so I don't know what is exactly going on....
Snowflakes used to work correctly on my android device with the version from last month. So I suspect one of the latest commit brake it...

**Comment by bartonhammond** [comment]
Make sure you use the new `src/lib/config.example.js` to copy to
`src/lib/config.js`.  Please look at the release notes.  If this fixes the
issue I will update the notes to clarify migration.

**Comment by ramsestom** [comment]
OK I didn't realized you modified the structure of 'config.js'. I changed it and it works now.
Should be good to return an error in the console when the 'config.js' file has incorect structure though, as currently it is failing silently.

**Comment by bartonhammond** [comment]
That's a good idea!  Would you mind making a PR?  

I think the only change would be in `lib/AppAuthToken.js` when the constructor is called.  Or maybe just remove that `config` option all together.  When I originally wrote it, I wasn't sure what to call it but since it was a string constant literal, I thought to make it user defined.  I don't know if anyone really cares what its called.  

Anyway, if you feel so inclined, I'd appreciate it.  Thanks for creating this issue.
