### ISSUE TITLE
Caught errors from network requests are generally not parseable

### ISSUE THREAD

**Issue by litch** [bartonhammond/snowflake#16]
https://github.com/bartonhammond/snowflake/blob/master/src/reducers/auth/authActions.js#L357

This causes red screen of death with a `Unable to convert NSDictionary into NSString error` - I think that the actual blowup is in the `createEvent` handler.  In any case, in my project I'm adapting from this I just raise a string, rather than the error object.

**Comment by litch** [comment]
BTW, for a good repro, just change your API_BASE_URL into something nonsensical.

**Comment by bartonhammond** [comment]
Thanks for creating the issue.  

Pretty much I've tried to keep the actions as simple as possible - that's why I just stuff the error obj into the payload.  If, in authAction.login, I try to process that error object, then I have to do it for all the try/catches in that and other *actions.  Instead, by modifying ErrorAlert to be sensitive to the presence of ```obj.message``` I need no other modifications.  

[https://github.com/bartonhammond/snowflake/blob/master/src/components/ErrorAlert.js#L48](https://github.com/bartonhammond/snowflake/blob/master/src/components/ErrorAlert.js#L48)
 
See release 0.0.4

**Comment by litch** [comment]
Thanks - incidentally as this upgrades and my app I'm building from of it evolves, I'm curious about how I might bring these low-level changes in. 

I may or may not try that git Magic but will keep you posted if I find anything else.  

Thank you for publishing this work.

**Comment by bartonhammond** [comment]
What I would do:

1)  click the "releases"
<img width="721" alt="screen shot 2015-12-09 at 8 51 33 am" src="https://cloud.githubusercontent.com/assets/1282364/11688413/1982503c-9e52-11e5-9c1e-729b3ce0affe.png">

2) click the link under the release e.g, 0.0.4, 
<img width="687" alt="screen shot 2015-12-09 at 8 52 39 am" src="https://cloud.githubusercontent.com/assets/1282364/11688439/3ee7d82e-9e52-11e5-86aa-2a522d694ad8.png">

3) look at the merged files: [https://github.com/bartonhammond/snowflake/commit/1528ca83c8438708a355eb11f6ee795c53de9d63](https://github.com/bartonhammond/snowflake/commit/1528ca83c8438708a355eb11f6ee795c53de9d63)

4) find the one you need:
<img width="1044" alt="screen shot 2015-12-09 at 8 55 00 am" src="https://cloud.githubusercontent.com/assets/1282364/11688483/913b1fdc-9e52-11e5-84df-1635fc9c43d3.png">

5) Either just copy the section modified and paste it appropriately.  Or just copy the whole file.  When you copy, it's best to go to the "raw" image, CTR-A to select everything, and CTR-C to copy...

<img width="1024" alt="screen shot 2015-12-09 at 8 58 16 am" src="https://cloud.githubusercontent.com/assets/1282364/11688570/0b60d680-9e53-11e5-900f-5f8ba38df461.png">
