### ISSUE TITLE
Jest & JSX components are *not* working w/ RN 0.17

### ISSUE THREAD

**Issue by bartonhammond** [bartonhammond/snowflake#29]

**Comment by JaxGit** [comment]
Inspired again by https://github.com/ertrzyiks/react-native-component-test , I figured out to use this workaround currently: 
transpile es6 syntax using custom scriptPreprocessor with babel-core 6, and apply additional 
    "unmockedModulePathPatterns": [
      "react",
      "react-addons-test-utils",
to fix Error: Failed to get mock metadata for some of the component tests. 

It's currently getting warning though: 
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).

I created a PR with this update on a new branch so that it's easier to be managed as you wish.

**Comment by bartonhammond** [comment]
Fixed SHA: 3fb493bd77779335047733ead0a192117516d741 - Thanks @JaxGit !

**Comment by JaxGit** [comment]
Glad to help. btw, to fix the warning, within __mocks__/react-native.js, ReactNative.TouchableOpacity = View should be changed to ReactNative.TouchableHighlight = View

**Comment by bartonhammond** [comment]
Fixed SHA: e6d4f6de74a6a62785beea15e00034b2ea6183dce - Thanks again @JaxGit !
