### ISSUE TITLE
Question about stability

### ISSUE THREAD

**Issue by scstarkey** [bartonhammond/snowflake#31]
Greetings Barton,

Thanks so much for this amazing foundation! I'm wondering, if we were to build a production app on top of this, would we be on stable ground? The nervousness I have with 0.0.8 is related not just to test failures, but also the warnings in the UI:

![image](https://cloud.githubusercontent.com/assets/1728638/12036704/0c0c6e8a-ae0e-11e5-8ae9-2e88e77f817a.png)

![image](https://cloud.githubusercontent.com/assets/1728638/12036708/10c16250-ae0e-11e5-9a1e-eced587631fc.png)

My assumption is this and the unit test failures around the Icon (which seem related) can be safely ignored since the app seems to function properly. The nervousness comes when building our own functionality such as replacing Parse with our own APIs and so forth. We'll be relying on the unit tests fairly heavily to make sure we don't step on each others' toes, so we can't just ignore the failures and warnings once we go to production.

Do you think it'll be fairly easy to stabilize and productionalize?

It's clear I have a lot to learn (I'm a Node novice and have come from a Java / Clojure background but mostly server-side), and the people I'm hiring [JavaScript / mobile developers] will hopefully have a lot more wisdom on this end, but I need to make a call about whether this tech is a good bet for our business, and this is the most complete example I've found. Any illumination you can provide would be extremely helpful!

Thanks again,

Stephen.

**Comment by bartonhammond** [comment]
Hi @scstarkey - Thanks for taking a look at Snowflake.

To me, if you've already determined that React Native is good enough for Production, then it's not a stretch to start w/ Snowflake.  The RN team moves very fast and it's hard to keep up with them.  

I had Snowflake working perfectly w/ release 0.15 but then 0.16 and 0.17 were released and it was a real task upgrading.  The RN team moved so fast they broke all my Jest JSX testing!  I'm hoping to get back at testing as I bring in some code I'm currently working on.

The big headache for me is keeping the Xcode project upgraded.  When doing a RN upgrade you have to be very careful what changes are made or lost when merging.  

As to those warnings - they only started popping up to the glass w/ RN 0.17 - I haven't bothered with them yet.  I'm hoping someone will do a PR (hint hint).

I've done a lot of development - over 30+ years - and having a 'starter project' is always great to give the team something more then a "hello world" experience.  For developers to come up to speed with Redux, they need something they can dig into - that's why I wrote Snowflake - I too needed to understand Redux and what it brings to the table.

I think Snowflake is worthy of being a 'starter app' for your production work.  I think Redux is an incredible step forward wrt State management. You may want to start w/ Snowflake so you have a 'straw man' to discuss amongst the team as to "best practices".  Most likely, over time, you'll make many changes that fit your "style" and your adaptation of snowflake will look very different from when you started.

But I think it will give you and your team a platform from which to grow.

By the way, I'm working on a NodeJS server implementation that can run locally and in the cloud that will be another "server" option along w/ Parse.com (see #30 for discussion).  I'm going to be using Hapi for the NodeJS Server and OpenShift for cloud hosting.  Not sure if that is anything your team would be interested in, but as I bring that into the project I'll be addressing these issues (testing, warnings, etc).

Thanks again for taking a look at Snowflake!

**Comment by scstarkey** [comment]
Thanks so much for the rapid and thoughtful reply! I will keep digging (my first project right now is reformatting the code to fit my anal retentive code style and the second will be changing how validation works so that it happens on "blur" instead of whenever you type something -- it's kind of jarring to see validation errors as your first interaction with an app.. hehe). Once that's clarified I will work on removing warnings and test failures if you don't get to it first.

Then it'll be time to fork into our private repository and start building a production app in earnest, including replacing Parse with our private APIs built in [compojure-api](https://github.com/metosin/compojure-api). Of course, user management will probably be farmed out to an enterprise vendor such as [StormPath](https://stormpath.com/). I don't trust Node in general, so a server-side implementation on that platform is a nonstarter for me. :-) It's a wonder I've invested so hard in react-native, but I just have to go with the best tool for the job and suck it up. Heh!

**Comment by bartonhammond** [comment]
Sounds like you have a plan.  

I looked at StormPath and it just confused the heck out of me so I just stayed w/ something simple that people could toss out and bring in their own flavor.

About the validation errors - yeah - everyone has a preference - my objective was to demonstrate one way.  I wouldn't probably wouldn't get away with that in a corp setting due to the UX guys, but hey, I'm retired, so I get to make those decisions now.  Hopefully Snowflake demonstrates something for everyone.

Good luck - if you figure out some of these issues and don't have time to do a PR - if you could open an issue on Snowflake and point me in the right direction for a fix, I'd appreciate it.

**Comment by bartonhammond** [comment]
Good luck!
