### ISSUE TITLE
RCTNetworking.sendRequest got 6 arguments, expected 7

### ISSUE THREAD

**Issue by yond** [bartonhammond/snowflake#95]
I am getting this error when running on android. 
Just cloned repo today and have latest react-native

**Comment by bartonhammond** [comment]
Note: I am no longer maintaining this repo.  See README.

**Comment by yond** [comment]
Oh yes. I see that but do you have any insight that can help on this issue? I have been using this boilerplate for a while now on a project and this has seriously stumped us

**Comment by bartonhammond** [comment]
I would upgrade all the libraries first.  I do that by copying all the libraries in the ```package.json``` and remove the references from it and use ```npm install --save xxx``` to get all the libraries at their current release level.

 I noticed RN has addressed many many things since the last Snowflake upgrade.  It's a lot of work for keep this project abreast of all the libraries involved.  

For some reasons, all the javascript libraries break backward compatibility all the time.  So finding out what changed is sometimes difficult.

**Comment by yond** [comment]
thank you

**Comment by yond** [comment]
Sorry one more question.. Do you start upgrading the dependencies on the
package.json and then try the devDependencies?

**Comment by bartonhammond** [comment]
I edit the package.json and remove all the names except for the ```native-button```.  I build and run this file.  When it is done the ```package.json``` is updated w/ the new dependancies.  Then I do ```git diff``` on it to get an idea of the libraries that have changed.  Then, for each one that's changed, I go read their release notes and docs to get a feel of what's changed so that when I try to build Snowflake, I have some idea of what library might be responsible.

```
npm install --save immutable key-mirror react-native    react-native-gifted-spinner    react-native-navbar    react-native-router-flux    react-native-simple-store    react-native-simpledialog-android    react-native-vector-icons    react-redux    redux    redux-thunk    regenerator    tcomb-form-native    underscore    validate.js
  
npm install --save-dev    babel-core    babel-jest    babel-preset-react-native    docker    istanbul    jest-cli    react    react-addons-test-utils    redux-mock-store

```

**Comment by bartonhammond** [comment]
Possibly a better way to have done Snowflake would have been to checked in all the ```node_modules``` so that all things were frozen.  It's something you'll want to consider in your own project too.

**Comment by wookiem** [comment]
@bartonhammond I'm really sorry to hear about the health issues Barton and I totally get the frustration with keeping snowflake updated.

@yond I'm also stuck waiting for a stable rebuild.  Have you made any progress on this?  If we get to a stable package.json, I'm thinking that we freeze it by removing the ^ from the package version number.  Then developers won't be suddenly stuck without a stable build.  Future changes to Snowflake (e.g. to take advantage of updates to react native) can be tackled without developer disruption.

**Comment by bartonhammond** [comment]
@wookiem - Great idea - using your suggestion, I have a working version now.  Will commit it so everyone has something that works.

**Comment by bartonhammond** [comment]
Please use stable release 1.0 [https://github.com/bartonhammond/snowflake/releases/tag/0.1.0](https://github.com/bartonhammond/snowflake/releases/tag/0.1.0 )

**Comment by wookiem** [comment]
That's terrific!  Thanks Barton.

**Comment by yond** [comment]
Thanks Barton. Running into some other issues with your latest.
Any idea of which library was causing the original issue?

**Comment by bartonhammond** [comment]
No idea - I didn't investigate.

My bad about checking in ```node_modules``` - instead I will just remove the ```^``` from package.json and user will have to ```npm install``` - working on this now.

**Comment by bartonhammond** [comment]
If you are having issues w/ this release that has the version numbers specific in the package.json, let's open up new issues.  

Sorry for the multiple releases today - I'm not feeling well and I'm making silly mistakes.
